### ISSUE TITLE
Test 4

### ISSUE THREAD

**Issue by SpidersInMyHair** [SpidersInMyHair/CS2521A1_Test#1]
Did test 4 on paper and unless I'm wrong the output is: 7, 2, 4, 5, 6, 9, 8, 0
The reason for the different output is because line 197 to line 199 has three previous() calls. Before the third and last previous() call, the cursor is already at the start of the list. Hence the set() call on line 200 should be invalid since it was not immediately preceded by a successful previous() call. So the set() should not change any value.

I think my working is right, but if someone could double check would be huge help.

**Comment by SpidersInMyHair** [comment]
This could also be coming from our set() function being different. Depending on how the cursor is handled in that function. But from what I can see, the set() function shouldn't move the cursor.

**Comment by bluecat999** [comment]
The set() function should not change the cursor. I will desk-check this on the train home (in an hour).

**Comment by bluecat999** [comment]
Issue resolved. I have also fixed the issue in my 'string' test.

Since that is the only occurrence of a set() after a previous() or findPrevious(), I am confident that the same bug does not exist anywhere else in the code.
